# Generated by Django 5.1.2 on 2025-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('missions', '0002_alter_mission_cat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_complete', False)), fields=('cat',), name='unique_active_mission_per_cat', violation_error_message='Cat already has an active mission.'),
        ),
    ]
